// Generated by `pracht typegen`. Do not edit manually.
import "@pracht/core";
import type { RouteLoaderData, RouteParamInput, SearchParamsInput } from "@pracht/core";

declare module "@pracht/core" {
  interface Register {
    routes: {
      "home": {
        path: "/";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/home")>;
      };
      "blog": {
        path: "/blog";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/blog")>;
      };
      "blueprint": {
        path: "/blueprint";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/blueprint")>;
      };
      "browser-timings": {
        path: "/blog/browser-timings";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/posts/browser-timings")>;
      };
      "controlled-inputs": {
        path: "/blog/controlled-inputs";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/posts/controlled-inputs")>;
      };
      "graphqls-missing-feature": {
        path: "/blog/graphqls-missing-feature";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/posts/document-authoring-missing-feature")>;
      };
      "drydock-release-defenses": {
        path: "/blog/drydock-release-defenses";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/posts/drydock-release-defenses")>;
      };
      "effect-subscriptions": {
        path: "/blog/effect-subscriptions";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/posts/effect-subscriptions")>;
      };
      "fed-up-with-belgium": {
        path: "/blog/fed-up-with-belgium";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/posts/fed-up-with-belgium")>;
      };
      "fragments-in-vdom": {
        path: "/blog/fragments-in-vdom";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/posts/fragments-in-vdom")>;
      };
      "graphql-abstract-types": {
        path: "/blog/graphql-abstract-types";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/posts/graphql-abstract-types")>;
      };
      "graphql-asterisk-problem": {
        path: "/blog/graphql-asterisk-problem";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/posts/graphql-asterisk-problem")>;
      };
      "graphql-development-workflow": {
        path: "/blog/graphql-development-workflow";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/posts/graphql-development-workflow")>;
      };
      "graphql-myths": {
        path: "/blog/graphql-myths";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/posts/graphql-myths")>;
      };
      "hydration-and-preact": {
        path: "/blog/hydration-and-preact";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/posts/hydration")>;
      };
      "llm-signals-debugging": {
        path: "/blog/llm-signals-debugging";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/posts/llm-signals-debugging")>;
      };
      "changed-my-mind-about-graphql": {
        path: "/blog/changed-my-mind-about-graphql";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/posts/mind-graphql")>;
      };
      "mixed-signals": {
        path: "/blog/mixed-signals";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/posts/mixed-signals")>;
      };
      "persisted-operations": {
        path: "/blog/persisted-operations";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/posts/persisted-operations")>;
      };
      "platform": {
        path: "/blog/platform";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/posts/platform")>;
      };
      "preact-use-id": {
        path: "/blog/preact-use-id";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/posts/preact-use-id")>;
      };
      "referential-stability-types": {
        path: "/blog/referential-stability-types";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/posts/referential-stability-types")>;
      };
      "resumed-hydration-preact": {
        path: "/blog/resumed-hydration-preact";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/posts/resumed-hydration-preact")>;
      };
      "secure-npm-publishing": {
        path: "/blog/secure-npm-publishing";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/posts/secure-npm-publishing")>;
      };
      "signals": {
        path: "/blog/signals";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/posts/signals")>;
      };
      "signals-debugging": {
        path: "/blog/signals-debugging";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/posts/signals-debugging")>;
      };
      "surgical-rendering": {
        path: "/blog/surgical-rendering";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/posts/signals-fetch")>;
      };
      "skew-based-diffing": {
        path: "/blog/skew-based-diffing";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/posts/skew-based-diff")>;
      };
      "state-in-vdom": {
        path: "/blog/state-in-vdom";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/posts/state-in-vdom")>;
      };
      "state-models": {
        path: "/blog/state-models";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/posts/state-models")>;
      };
      "state-vs-signals": {
        path: "/blog/state-vs-signals";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/posts/state-vs-signals")>;
      };
      "suspense-data-ssr": {
        path: "/blog/suspense-data-ssr";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/posts/suspense-data-ssr")>;
      };
      "tracking-context": {
        path: "/blog/tracking-context";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/posts/tracking-context")>;
      };
      "unreliable-vendors": {
        path: "/blog/unreliable-vendors";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/posts/unreliable-vendors")>;
      };
      "vdom-compilers": {
        path: "/blog/vdom-compilers";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/posts/vdom-compilers")>;
      };
      "why-computed-matters": {
        path: "/blog/why-computed-matters";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/posts/why-computeds-matter")>;
      };
    };
    apiRoutes: {
    };
  }
}

export {};
