// Generated by `pracht typegen`. Do not edit manually.
import { createHref } from "@pracht/core";
import type { HrefRouteDefinition } from "@pracht/core";

export const routes = [
  {
    id: "home",
    path: "/",
  },
  {
    id: "blog",
    path: "/blog",
  },
  {
    id: "blueprint",
    path: "/blueprint",
  },
  {
    id: "browser-timings",
    path: "/blog/browser-timings",
  },
  {
    id: "controlled-inputs",
    path: "/blog/controlled-inputs",
  },
  {
    id: "graphqls-missing-feature",
    path: "/blog/graphqls-missing-feature",
  },
  {
    id: "drydock-release-defenses",
    path: "/blog/drydock-release-defenses",
  },
  {
    id: "effect-subscriptions",
    path: "/blog/effect-subscriptions",
  },
  {
    id: "fed-up-with-belgium",
    path: "/blog/fed-up-with-belgium",
  },
  {
    id: "fragments-in-vdom",
    path: "/blog/fragments-in-vdom",
  },
  {
    id: "graphql-abstract-types",
    path: "/blog/graphql-abstract-types",
  },
  {
    id: "graphql-asterisk-problem",
    path: "/blog/graphql-asterisk-problem",
  },
  {
    id: "graphql-development-workflow",
    path: "/blog/graphql-development-workflow",
  },
  {
    id: "graphql-myths",
    path: "/blog/graphql-myths",
  },
  {
    id: "hydration-and-preact",
    path: "/blog/hydration-and-preact",
  },
  {
    id: "llm-signals-debugging",
    path: "/blog/llm-signals-debugging",
  },
  {
    id: "changed-my-mind-about-graphql",
    path: "/blog/changed-my-mind-about-graphql",
  },
  {
    id: "mixed-signals",
    path: "/blog/mixed-signals",
  },
  {
    id: "persisted-operations",
    path: "/blog/persisted-operations",
  },
  {
    id: "platform",
    path: "/blog/platform",
  },
  {
    id: "preact-use-id",
    path: "/blog/preact-use-id",
  },
  {
    id: "referential-stability-types",
    path: "/blog/referential-stability-types",
  },
  {
    id: "resumed-hydration-preact",
    path: "/blog/resumed-hydration-preact",
  },
  {
    id: "secure-npm-publishing",
    path: "/blog/secure-npm-publishing",
  },
  {
    id: "signals",
    path: "/blog/signals",
  },
  {
    id: "signals-debugging",
    path: "/blog/signals-debugging",
  },
  {
    id: "surgical-rendering",
    path: "/blog/surgical-rendering",
  },
  {
    id: "skew-based-diffing",
    path: "/blog/skew-based-diffing",
  },
  {
    id: "state-in-vdom",
    path: "/blog/state-in-vdom",
  },
  {
    id: "state-models",
    path: "/blog/state-models",
  },
  {
    id: "state-vs-signals",
    path: "/blog/state-vs-signals",
  },
  {
    id: "suspense-data-ssr",
    path: "/blog/suspense-data-ssr",
  },
  {
    id: "tracking-context",
    path: "/blog/tracking-context",
  },
  {
    id: "unreliable-vendors",
    path: "/blog/unreliable-vendors",
  },
  {
    id: "vdom-compilers",
    path: "/blog/vdom-compilers",
  },
  {
    id: "why-computed-matters",
    path: "/blog/why-computed-matters",
  },
] as const satisfies readonly HrefRouteDefinition[];

export const href = createHref(routes);
